Fix pinning of machine_type
runatlantis/terraform-gce-atlantis pull request #149
Opened 2024-04-18 09:17 UTC by dimisjim

## what
Achieve pinning of COS image by fixing behavior of machine_image var and input to downstream container module

## why
* Be able to pin image and not always use latest one

## references
* Closes #114 (which needs to be reopened to be closed again with this)

2024-04-18 13:28 UTC, dimisjim commented
```
remote: Permission to dimisjim/terraform-gce-atlantis.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/dimisjim/terraform-gce-atlantis/': The requested URL returned error: 403
```

not sure what it causing exactly the error in the CI run but I have just enabled workflows in the forked repo, so maybe you can try running it again 👍

2024-04-19 21:48 UTC, d-costa commented
@dimisjim that error is due to the `terraform-docs`trying to fixing the docs, and fails to commit - which makes sense
we should probably disable the `git-push` flag when the workflow runs on forks

2024-04-19 22:20 UTC, d-costa commented
This docker oneliner should inject the fix locally:

```sh
docker run --rm --volume "$(pwd):/terraform-docs" -u $(id -u) quay.io/terraform-docs/terraform-docs:0.17.0 markdown --output-file README.md --output-mode inject /terraform-docs
```

Source: <https://github.com/terraform-docs/terraform-docs?tab=readme-ov-file#using-docker>

2024-04-20 13:30 UTC, dimisjim commented
cool, should be done :+1:

2024-04-21 10:10 UTC, bschaatsbergen requested changes
Hey @dimisjim, thanks for taking the time to submit this pull request - good spot! 👏🏼 

Allow me to share a few thoughts on why this only partially solves it, it's expecting that `machine_image` is always set.

Note, `machine_image` has a null default, and we rely on the data source `google_compute_image.cos` to fetch the machine image for the user if they're not specifying `machine_image`.

See the condition on `source_image` in `google_compute_instance_template.default.disk`.

I would recommend introducing a similar condition on `cos_image_name` like what we do on `source_image`, combined with your PR.

2024-04-21 10:20 UTC, dimisjim commented
Thanks for the feedback @bschaatsbergen 

Good catch!

Fix is provided here:

2024-05-14 18:54 UTC, bschaatsbergen commented
Sorry for the delayed review on my side, I need to test whether this could be a breaking change or not.. have you already tested it on your side @dimisjim?

2024-05-14 20:36 UTC, dimisjim commented
@bschaatsbergen yes, works as expected

2024-10-03 16:11 UTC, joe1981al commented
Might I suggest also parsing `cos_project` from the input?  It would be similar to what you've done but would be second item in the split, otherwise "cos-cloud" which is the default in the module being used.  Not sure if necessary, but might be useful.

2024-11-27 13:38 UTC, bschaatsbergen submitted a review, later dismissed

2024-12-03 17:31 UTC, d-costa commented
I'd also suggest making `data "google_compute_image" "cos"` conditional based on the presence of `var.machine_image`, to avoid reading it even when machine_type is specified

2025-01-09 01:13 UTC, cblkwell commented
Hey folks, we really need to get this new version out -- can we consider replicating this change in another PR if @dimisjim isn't able to fix the commit signing issue?

2025-01-09 11:00 UTC, closed without merging

2025-01-09 11:07 UTC, dimisjim commented
@cblkwell opened a new one: https://github.com/runatlantis/terraform-gce-atlantis/pull/172